config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"
    root 'reception#dashboard'

  resources :doctors
  resources :patients do
    resources :appointments
  resources :educations, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :date, presence: true
  validate :date_cannot_be_in_the_past
  validates :cause, presence: true
  validates :urgent, inclusion: { in: [true, false] }

  private

  def date_cannot_be_in_the_past
    errors.add(:date, "can't be in the past") if date.present? && date < DateTime.now
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # has_one :education, dependent: :destroy
  has_many :educations
  has_many :appointments
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :title, presence: true
  validates :available, presence: true
  validates :speciality, presence: true
  validates :experience, presence: 2..6

  def average_degree_score
    total_score = educations.sum(:score)
    total_score / educations.count.to_f if educations.count.positive?

    has_one :education, dependent: :destroy
  end
end

app/models/education.rb
class Education < ApplicationRecord

  validates :university, presence: true
  validates :degree_name, presence: true
  validates :score, numericality: { greater_than: 50, less_than: 100 }

  belongs_to :doctor
end

app/models/patient.rb
class Patient < ApplicationRecord

  has_many :appointments
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :insurance, inclusion: { in: %w(Private Public) }
  validates :cured, inclusion: { in: [true, false] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
    @doctor = @appointment.doctor
    @patient = @appointment.patient
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctor.all
  end

  def new
   @doctor = Doctor.new
  end

   def show
     @doctor = Doctor.find(params[:id])
     @appointments = @doctor.appointments.future_appointments
   end

   def make_unavailable
    # Implement logic to make the doctor unavailable and delete appointments
  end
end


  def create
    @doctor = Doctor.new(doctors_params)
    @doctor.save
    redirect_to doctor_path(@doctor)
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    @doctor.update(doctors_params)
    redirect_to doctor_path(@doctor)
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path, status: :see_other

  end

  private

  def doctors_params
    params.require(:doctor).permit(:first_name, :last_name, :title, :available, :speciality, :experience)
  end

app/controllers/education_controller.rb
class EducationController < ApplicationController
  before_action :set_doctor
  before_action :set_education, only: [:edit, :update, :destroy]

  def index
    @educations = @doctor.educations
  end

  def new
    @education = @doctor.educations.build
  end

  def create
    @education = @doctor.educations.build(education_params)
    if @education.save
      redirect_to doctor_educations_path(@doctor), notice: 'Education/Degree was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @education.update(education_params)
      redirect_to doctor_educations_path(@doctor), notice: 'Education/Degree was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @education.destroy
    redirect_to doctor_educations_path(@doctor), notice: 'Education/Degree was successfully destroyed.'
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def set_education
    @education = @doctor.educations.find(params[:id])
  end

  def education_params
    # Define your education parameters
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.sick_patients
  end

  def show
    @patient = Patient.find(params[:id])
    @appointments = @patient.appointments.future_appointments
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    # Define your patient parameters
  end
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController

  def dashboard
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/views/doctors/edit.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :title %>
  <%= f.input :available %>
  <%= f.input :speciality %>
  <%= f.input :experience %>
  <%= f.submit %>
<% end %>

app/views/doctors/index.html.erb
<h1>Tony's Private Clinic for Mutants</h1>

<ul>
  <% @doctors.each do |doctor| %>
    <li><%= link_to "#{doctor.first_name} #{doctor.last_name} (#{doctor.speciality})", doctor_path(doctor) %></li>
  <% end %>
</ul>


<%= link_to "Add a new doctor", new_doctor_path %>

app/views/doctors/new.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :title %>
  <%= f.input :available %>
  <%= f.input :speciality %>
  <%= f.input :experience %>
  <%= f.submit %>
<% end %>

app/views/doctors/show.html.erb
    <ul>
    <li><%= @doctor.first_name %></li>
    <li><%= @doctor.last_name %></li>
    <li><%= @doctor.title %></li>
    <li><%= @doctor.available %></li>
    <li><%= @doctor.speciality %></li>
    <li><%= @doctor.experience %></li>
    </ul>

<%= link_to "Delete",
  doctor_path(@doctor),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<%= link_to "Change your Doctor", edit_doctor_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Sick Patients</h1>

<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.name, patient_path(patient) %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Patient', new_patient_path %>